name: Ubuntu

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest MSVC 2019",
            os: windows-latest,
            build_type: "Release",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
          - {
            name: "Ubuntu Latest",
            os: ubuntu-latest,
            build_type: "Release"
          }
          - {
            name: "macOS Latest Clang",
            os: macos-latest,
            build_type: "Release"
          }

    steps:
      - uses: actions/checkout@v2
      #- name: fetchtags
      #  run: git fetch --unshallow --tags
      - name: Checkout Submodules
        run: git submodule init && git submodule update
      - name: Download Conan package manager
        run: |
           pip3 install wheel setuptools
           pip3 install conan
           conan --version
      - name: Install Dependencies with Conan
        run: |
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan install -if build .          
      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
      - name: Build with CMake
        run: cmake --build build --config ${{ matrix.config.build_type }}
