name: "Multi-OS using IXWebSocket"

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest MSVC 2019",
            os: windows-latest,
            build_type: "Release",
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }
          - {
            name: "Ubuntu Latest",
            os: ubuntu-latest,
            build_type: "Release"
          }
          - {
            name: "macOS Latest Clang",
            os: macos-10.15,
            build_type: "Release"
          }

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Download Conan package manager
        run: |
           pip3 install wheel setuptools
           pip3 install conan
           conan --version
      - name: Install Dependencies with Conan (Windows)
        if: ${{ matrix.config.os == 'windows-latest' }}
        run: |
          conan install -if build --build=missing .
      - name: Install Dependencies with Conan (macOS 10.13)
        if: ${{ matrix.config.os == 'macos-10.15' }}
        run: |
          conan install -if build --build=missing -s os.version=10.13 .
      - name: Install Dependencies with Conan (Ubuntu)
        if: ${{ matrix.config.os == 'ubuntu-latest' }}
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan install -if build --build=missing .
      - name: Configure CMake
        if: ${{ matrix.config.os != 'macos-10.15' }}
        run: |
          cmake -S . -B build -DUSE_IX_WEBSOCKET=ON -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
      - name: Configure CMake (macOS 10.13+)
        if: ${{ matrix.config.os == 'macos-10.15' }}
        run: |
          cmake -S . -B build -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DUSE_IX_WEBSOCKET=ON -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }}
      - name: Build with CMake
        run: |
          cmake --build build --config ${{ matrix.config.build_type }}
